openai:
  token: ${OPENAI_TOKEN}
  textRemoteUrl: https://api.openai.com/v1/chat/completions
  voiceTranscriptionRemoteUrl: https://api.openai.com/v1/audio/transcriptions

bot:
  name: chatGPT-telegram-bot
  token: ${BOT_TOKEN}
