openai:
  token: ${OPENAI_TOKEN}
  textRemoteUrl: https://api.openai.com/v1/chat/completions

bot:
  name: chatGPT-telegram-bot
  token: ${BOT_TOKEN}
#  model: gpt-4o-mini
#  model: dall-e-2 # to create images
