name: CD
on:
  workflow_run:
    workflows: CI
    branches: [main]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: mvn -DskipTests=true package
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_CREDENTIALS_USR }}
          password: ${{ secrets.DOCKERHUB_CREDENTIALS_PSW }}
      - name: build and push Docker image
        run: |
          docker build . -t alekckorsh/telegramaibot
          docker push alekckorsh/telegramaibot:latest