  name: CI
  on:
    push:
      branches:
        - main
  jobs:
    cache:
      runs-on: ubuntu-latest
      steps:
        - name: get repository code
          uses: actions/checkout@v4
        - name: set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
            cache: 'maven'
    test:
       needs: cache
       runs-on: ubuntu-latest
       steps:
         - name: get repository code
           uses: actions/checkout@v4
         - name: set up JDK 21
           uses: actions/setup-java@v4
           with:
             distribution: 'temurin'
             java-version: '21'
             cache: 'maven'
         - name: clean and compile project with Maven
           run: mvn clean compile
         - name: run tests
           run: mvn test
    package:
       needs: test
       runs-on: ubuntu-latest
       continue-on-error: true
       steps:
         - name: get repository code
           uses: actions/checkout@v4
         - name: set up JDK from Matrix
           uses: actions/setup-java@v4
           with:
            distribution: 'temurin'
            java-version: '21'
            cache: 'maven'
         - name: package project
           run: mvn -DskipTests=true package


